spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081


