

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BankingDB
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # Can be 'create', 'update', or 'validate' based on your requirements
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: BankingDB
